### ISSUE TITLE
Understanding how `setMounted` works

### ISSUE THREAD

**Issue by alireza-ahmadi** [sonnat/sonnat-ui#5]
I've been checking out the code-base and saw this pattern in multiple components:

```jsx
const [isMounted, setMounted] = useState(false);

useEffect(() => {
  setMounted(true);
  return () => setMounted(false);
}, []);
```

However, based on my understanding, changing the state in the `useEffect` cleanup wouldn't change anything because the re-render must happen for the change to take effect (even for the callbacks to be able to access the changed portion of the state), and an already unmounted component wouldn't re-render.

Am I missing something, and there is a special use case(like rehydration or such) for this, or is this just an implementation issue?

**Comment by mimshins** [comment]
> I've been checking out the code-base and saw this pattern in multiple components:
> 
> ```js
> const [isMounted, setMounted] = useState(false);
> 
> useEffect(() => {
>   setMounted(true);
>   return () => setMounted(false);
> }, []);
> ```
> 
> However, based on my understanding, changing the state in the `useEffect` cleanup wouldn't change anything because the re-render must happen for the change to take effect (even for the callbacks to be able to access the changed portion of the state), and an already unmounted component wouldn't re-render.
> 
> Am I missing something, and there is a special use case(like rehydration or such) for this, or is this just an implementation issue?

First of all, thanks for checking out the code-base.

The main purpose of this pattern is to fix the `Warning: Can't perform a React state update on an unmounted component.` warning. The most common cause of this warning is when an asynchronous useState is in the stack, but user leaves the page before it completes.

However, the cleanup isn't necessary in our case, we can just simply do:
```js
useEffect(() => void setMounted(true), [])
```

The cleanup function is left there because we were used to use a custom hook like below:
```js
const useIsMounted = () => {
  const isMounted = useRef(false);
  useEffect(() => {
    isMounted.current = true;
    return () => isMounted.current = false;
  }, []);
  return isMounted;
};
```
I'm going to remove the unnecessary cleanup function and bring back our custom hook on the next patch.
Thanks for your contribution.
